Feature/tornado fetcher publisher
ONSdigital/sdx-seft-publisher-service pull request #8
Opened 2017-07-17 08:56 UTC by Dave-Haynes

Status today:
* Unit tests run and pass locally and in CF.
* Service fails to load keys locally or in CF.
* Rabbit connection as yet untested in CF.

2017-07-17 10:25 UTC, JamesGardiner requested changes
Can you add a codecov.yml to this and set this up for codacy as well?

2017-07-17 10:25 UTC, JamesGardiner commented on .travis.yml
> +  - "3.5"
Test against 3.6 as well - this is what we will use on CF

2017-07-17 10:25 UTC, JamesGardiner commented on .travis.yml
> +install: make depinstall
This is failing in Travis

2017-07-17 10:25 UTC, JamesGardiner commented on app/encrypter.py
> +KID = 'SEFT'
Will this be loaded from the environment eventually?

2017-07-17 10:25 UTC, JamesGardiner commented on app/encrypter.py
> +import jwt
Highly pedantic comment of the day - can we do imports alphabetically?

2017-07-17 10:25 UTC, JamesGardiner commented on app/ftpclient.py
> +    def __init__(self, user, password, host, port, timeout=30, **kwargs):
Is the kwarg  unpacking used at all? If not, can we just use explicit keyword params?

2017-07-17 10:25 UTC, JamesGardiner commented on app/ftpclient.py
> +        except Exception as e:
Does this need to swallow all exceptions, or should we be more selective?

2017-07-17 10:25 UTC, JamesGardiner commented on app/main.py
> +            log.warning("Could not read key {0}".format(pub_fp))
Might be useful to see the stacktrace of the original exception

2017-07-17 10:25 UTC, JamesGardiner commented on app/main.py
> +        "%(asctime)s %(levelname)-7s %(name)s|%(message)s")
This format should be taken from the common library formatter

2017-07-17 10:25 UTC, JamesGardiner commented on app/main.py
> +    log = logging.getLogger("pika")
again, this functionality is in the common library

2017-07-17 10:25 UTC, JamesGardiner commented on app/main.py
> +    interval_ms = 30 * 60 * 1000
This should probably be configurable from the env

2017-07-17 10:25 UTC, JamesGardiner commented on app/publisher.py
> +    def __init__(self, amqp_url, queue_name, log=None, **kwargs):
Can we use explicit kwargs

2017-07-17 10:25 UTC, JamesGardiner commented on app/test/decrypter.py
> +import jwt
alphabetized

2017-07-17 10:25 UTC, JamesGardiner commented on app/test/test_ftp.py
> +        self.root = tempfile.mkdtemp()
In general, we should not be using the local filesystem in CF.

2017-07-17 10:25 UTC, JamesGardiner commented on app/test/test_ftp.py
> +    def setUp(self):
method names should comply with pep8

2017-07-18 09:10 UTC, warrenbailey requested changes

2017-07-18 09:10 UTC, warrenbailey commented on app/encrypter.py
> +KID = 'SEFT'
It should be configurable and once we move it to sdx-decrypt I think we do that, for now I'd be tempted to leave it as is.

2017-07-18 09:10 UTC, warrenbailey commented on app/main.py
> +        log = logging.getLogger("sdx.seft")
Can the logger be defined at class level? Seems odd to redefine it every time we run transfer_files

2017-07-18 09:10 UTC, warrenbailey commented on app/main.py
> +    p.add_argument(
Why are we defining config via command line arguments? This goes against the other services that all use environment variables?

2017-07-18 09:10 UTC, warrenbailey commented on app/main.py
> +    services = json.loads(os.getenv("VCAP_SERVICES", "{}"))
This is specific to getting config from CF. I appreciate you're using CF for testing but production code will need  to be configured from environment variables as the target environment is NGD.

Therefore we should remove this line.

2017-07-18 09:10 UTC, warrenbailey commented on app/ftpclient.py
> +            except Exception as e:
Agree with James, can we avoid catching Exception and be a bit more fine grained?

2017-07-18 09:10 UTC, warrenbailey commented on app/main.py
> +            uri = services["rabbitmq"][0]["credentials"]["protocols"]["amqp"]["uri"]
How will this work outside of CF?

2017-07-18 10:11 UTC, Dave-Haynes commented on app/test/test_ftp.py
> +    def setUp(self):
Flake8 passes for me.

2017-07-18 10:13 UTC, Dave-Haynes commented on app/test/test_ftp.py
> +        self.root = tempfile.mkdtemp()
It's a test for an FTP server, so it needs a place to keep its files. I think that's legitimate in this case. If CF can't support that, its a deficiency in CF and someone should fix that.

2017-07-18 10:27 UTC, Dave-Haynes commented on app/main.py
> +    p.add_argument(
Required for testing in CF. We don't need them in NGD.

2017-07-18 10:32 UTC, Dave-Haynes commented on app/ftpclient.py
> +            except Exception as e:
There's no case I can think of where we could take a different action depending on the exception.

2017-07-18 10:53 UTC, Dave-Haynes commented on app/ftpclient.py
> +        except Exception as e:
There may be different reasons for failure, but there isn't any choice of action we can take based on the type of exception. We either connect or we don't. If we don't, we can't proceed.

2017-07-18 14:08 UTC, warrenbailey requested changes

2017-07-18 14:08 UTC, warrenbailey commented on app/main.py
> +                    data["contents"] = base64.standard_b64encode(job.contents).decode("ascii")
Rather than "contents" it should be "file"
We also need a "filename" attribute with the name of the file.

2017-07-19 09:22 UTC, necrophonic commented on Makefile
> +.PHONY: build dev start test
Makefile doesn't work in clean environment - should be updated à la https://github.com/ONSdigital/sdx-receipt-ctp/blob/master/Makefile

2017-07-19 12:01 UTC, warrenbailey requested changes

2017-07-19 12:01 UTC, warrenbailey commented on README.md
> +| PORT                 | -       | The port to bind to
Probably should add the environment variables to the README

2017-07-19 12:01 UTC, warrenbailey commented on app/ftpclient.py
> +            except Exception as e:
OK

2017-07-19 12:01 UTC, warrenbailey commented on app/test/test_ftp.py
> +$ cf push seft-publisher-unittest
This probably should be in the README

2017-07-19 12:01 UTC, warrenbailey commented on requirements.txt
> +sdx-common>=0.7.0
We specifically changed this in all other repos to pin the SDX common version

2017-07-19 13:04 UTC, warrenbailey commented
FYI none of your commits are showing as verified, probably need to check your keys

2017-07-20 07:14 UTC, warrenbailey submitted a review, later dismissed
Waiting for @JamesGardiner before merging

2017-07-20 10:04 UTC, JamesGardiner approved these changes

2017-07-20 10:07 UTC, merged